services:
  mongo:
    image: mongo:7
    container_name: tiny-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - tiny_net

  redis:
    image: redis:7
    container_name: tiny-redis
    networks:
      - tiny_net

  backend:
    build:
      context: ./backend
    container_name: tiny-backend
    environment:
      BASE_URL: http://localhost:8090
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: tiny_url
      MONGO_COLLECTION: urls
      REDIS_URL: redis://redis:6379/0
      REDIS_TTL_SECONDS: 86400
      CODE_LEN: 7
    ports:
      - "8090:8090"
    depends_on:
      - mongo
      - redis
    networks:
      - tiny_net

  frontend:
    build:
      context: ./frontend
    container_name: tiny-frontend
    environment:
      VITE_API_BASE: http://localhost:8090
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - tiny_net

volumes:
  mongo_data:

networks:
  tiny_net:
